# Generated by Django 5.2.3 on 2025-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-first_submit_at'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interested_in_model',
            field=models.CharField(blank=True, choices=[('SPLENDOR_PLUS', 'Splendor Plus'), ('SUPER_SPLENDOR', 'Super Splendor'), ('XTREME_125R', 'Xtreme 125R'), ('DESTINI_125', 'Destini 125'), ('PLEASURE_PLUS', 'Pleasure Plus'), ('XOOM_125', 'Xoom 125'), ('XTREME_160R', 'Xtreme 160R'), ('HF_DELUXE', 'HF Deluxe'), ('XPULSE_200', 'Xpulse 200'), ('SUPER_SPLENDOR_XTEC', 'Super Splendor Xtec'), ('XTREME_160R_4V', 'Xtreme 160R 4V'), ('MAVRICK_440', 'Mavrick 440'), ('DESTINI_PRIME', 'Destini Prime'), ('XOOM_160', 'Xoom 160'), ('PLEASURE', 'Pleasure'), ('SPLENDOR_PLUS_XTEC', 'Splendor Plus Xtec'), ('PASSION_PLUS', 'Passion Plus'), ('XPULSE_210', 'Xpulse 210'), ('XOOM', 'Xoom'), ('XOOM_110', 'Xoom 110'), ('GLAMOUR', 'Glamour'), ('GLAMOUR_XTEC', 'Glamour Xtec')], max_length=50, null=True, verbose_name='Interested In Model'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='finance_bank',
            field=models.CharField(blank=True, choices=[('HERO_FINCORP', 'Hero Fincorp Ltd'), ('IDFC_BANK', 'IDFC Bank'), ('HDB_BANK', 'HDB Bank'), ('CWC_LTD', 'CWC Ltd'), ('SMFG_BANK', 'SMFG Bank'), ('AU_SMALL_FIN_BANK', 'Au Small Fin. Bank'), ('HINDUJA_LEYLAND_BANK', 'Hinduja Leyland Bank'), ('TATA_CAPITAL', 'Tata Capital Ltd'), ('RBL_BANK', 'RBL Bank'), ('MUTHOOT_BANK', 'Muthoot Bank'), ('LT_FIN_LTD', 'L & T Fin. Ltd'), ('HDFC_BANK', 'HDFC Bank'), ('CHOLA_MANDALAM_BANK', 'Chola Mandalam Bank')], max_length=50, null=True, verbose_name='Finance Bank'),
        ),
    ]
